Taskkill /IM "TokenUpdater.exe" /F
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
TokenUpdater.exe > log.txt
